version: '3'

services:
  
  ngs2-toy:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: Rscript -e 'rmarkdown::render("./NGS2_WITNESS_Cycle4_h15_TOY.rmd")'
  
  ngs2-fieldwork:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: Rscript -e 'rmarkdown::render("./NGS2_WITNESS_Cycle4_fieldwork.rmd")'

  ngs2-tests:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: Rscript -e 'rmarkdown::render("./NGS2_WITNESS_Cycle4_tests.rmd")'
    
  ngs2-c1:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h1.R

  ngs2-c2:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h2.R

  ngs2-c3:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h3.R

  ngs2-c4:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h4.R

  ngs2-c5:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h5.R

  ngs2-c6:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h6.R

  ngs2-c7:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h7.R

  ngs2-c8:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h8.R

  ngs2-c9:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h9.R

  ngs2-c10:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h10.R

  ngs2-c11:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h11.R

  ngs2-c12:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h12.R

  ngs2-c13:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h13.R

  ngs2-c14:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h14.R

  ngs2-c15:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h15.R

  ngs2-c16:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h16.R

  ngs2-c17:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h17.R

  ngs2-c18:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h18.R

  ngs2-c19:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h19.R

  ngs2-c20:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h20.R

  ngs2-c21:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h21.R

  ngs2-c22:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h22.R

  ngs2-c25:
    image: gallupgovt/ngs2_witness:stable
    volumes:
      - ./:/app
    command: R CMD BATCH h25.R

