---
title: "Group Innovation under Competition and Uncertanity - Cycle 3 Results"
author: "Pablo Diego-Rosell, PhD  - Gallup"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    number_sections: yes
    theme: united
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
rm(list = ls(all = TRUE))
dd <- getwd()
od <- getwd()
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, strip.white=TRUE, tidy=TRUE)
# load libraries
if (!require("pacman")) install.packages("pacman")
library ("pacman")
pacman::p_load(rstan, rstanarm, ggplot2, Hmisc, httr, bridgesampling, DT, dplyr, bayesplot, knitr, lme4, RCurl, formatR, caret, pROC, formatR, foreach, doParallel, forcats, tidyr, car)

# download scripts and data
dlScripts <- function (scriptNames) {
  fileHolder <- getURL(paste(githubRepo, scriptNames, sep = "/"), ssl.verifypeer = FALSE)
  fileConn<-file(scriptNames)
  writeLines(fileHolder, fileConn)
  close(fileConn)
}
githubRepo <- "https://raw.githubusercontent.com/GallupGovt/ngs2/master/cycle3/Boomtown/Analysis"
setup <- c("functions.R", "analytics.R", "survey_tests_cycle_3_code.R")
hypotheses <- c("h25.R")
data <- c("game_data.csv", "game_data_group.csv", "survey_data.csv", "game_survey_data.csv")
lapply(c(setup, hypotheses, data), dlScripts)
```

```{r run_scripts, include=F}
# run scripts in order
source("functions.R")
factorial <- read.csv(file="game_data.csv")
factorialGroup <- read.csv(file="game_data_group.csv")
factorialGroup2 <- factorialGroup
factorialGroup2[] <- lapply(factorialGroup, factor)
factorialGroup2$conformity <- as.numeric(factorialGroup$conformity)
factorialGroup2$grmot1 <- as.numeric(factorialGroup$grmot1)
factorialGroup2$grmot2 <- as.numeric(factorialGroup$grmot2)
factorialGroup2$risk <- as.numeric(factorialGroup$risk)
factorialGroup2$density <- as.numeric(factorialGroup$density)
factorialGroup2$centralization <- as.numeric(factorialGroup$centralization)
factorialGroup2$leaderWeight <- as.numeric(factorialGroup$leaderWeight)
factorialGroup2$innovation <- as.numeric(factorialGroup$innovation)-1
factorialGroup <- factorialGroup2
factorialGroup$innovation <- factorialGroup$innovation+2
survey <- read.csv(file="survey_data.csv")
game_survey_data <- read.csv(file="game_survey_data.csv")
source("analytics.R")
source("survey_tests_cycle_3_code.R")
nChains <- 3
nIter <- 1000
source("h25.R")
```

### Hypothesis 25. Group Aggregate (T2) and Group Motivation to Innovate

- Null: Group Aggregate motivation to innovate (T2) will not increase Group Motivation to Innovate.

```{r h25null}
load (file ="bayesGlmer_h25.1_h25.0")
summary(fittedGlmer, digits = 2)
```
- Prediction 1: Group Aggregate motivation to innovate (T2) will increase Group Motivation to Innovate.

```{r h25BFs}
BFs25 <-read.csv(paste(od, "BFs25.csv", sep = '/'))                      
BFs25
```

End Time: `r format(Sys.time(), '%d %B, %Y')`

<br />
<br />
<br />